---
- name: Patch RHEL server
  hosts: all
  # become: true

  # List of possible variables can for example be found here:
  # https://cloudspinx.com/list-of-ansible-os-family-os-distribution-facts/
  
  tasks:
    - name: Update packages on Red Hat-based systems
      ansible.builtin.package:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "Fedora"

    - name: Update packages on Debian-based systems
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"

    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true
      when: ansible_facts['os_family'] == "Windows"      
