---
- name: Patch servers according to OS type
  hosts: all
  #become: true

  # List of possible variables can for example be found here:
  # https://cloudspinx.com/list-of-ansible-os-family-os-distribution-facts/
  
  tasks:
    - name: Update packages on systems
      # Package can be used as a generic approach to different Operating system types, see:
      # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/package_module.html#ansible-collections-ansible-builtin-package-module
      ansible.builtin.package:
        name: "*"
        state: latest

    - name: Update packages on Red Hat-based systems
      # https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/dnf_module.html#ansible-collections-ansible-builtin-dnf-module
      # could also use yum or even dnf5
      ansible.builtin.dnf:
        name: "*"
        state: latest
      when: ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "CentOS" or ansible_facts['distribution'] == "Fedora"

    - name: Update packages on Debian-based systems
      # Docu here: https://docs.ansible.com/projects/ansible/latest/collections/ansible/builtin/apt_module.html#ansible-collections-ansible-builtin-apt-module
      ansible.builtin.apt:
        upgrade: dist
      when: ansible_facts['distribution'] == "Debian" or ansible_facts['distribution'] == "Ubuntu"

    - name: Install all updates and reboot as many times as needed
      # https://docs.ansible.com/projects/ansible/latest/collections/ansible/windows/win_updates_module.html#ansible-collections-ansible-windows-win-updates-module
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true
      when: ansible_facts['os_family'] == "Windows"      
