- name: Hello Events
  hosts: localhost
  sources:
  - ansible.eda.kafka:
       host: kafka
       port: 9092
       topic: orders
  rules:
  - name: Say Hello
    condition: event.target_os == "linux" and event.tracking_id == 345
    action:
       debug:
         msg: “{{ event }}”
